In [1]:
#Step 1: Load test.csv and train.csv
import pandas as pd
#Load train.csv
tr_url = "https://storage.googleapis.com/kaggle-competitions-data/kaggle/3136/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1514683831&Signature=MMjwcVhnoF2QiFlFlpA88nwSykIbl%2FFdqE%2Bodi8y8oJjTC75rOWtmPnX1KrlUY%2Bl%2FjlosfZ5Wq6aGsOtLkm47ythlR4ybzn51MV6n5buxkInY5fyKVDmXk9Q%2BR3OOiM7hdbEv%2FFuNjuzPhR3CZMM3ATWw7vntkJYns0gmKC72zvJBfR%2BOEAV4EQO6ghRc39guJ49yv9lrr5ToWoGEfnzq45GdoFTosnTSQExfQApHJBMgq0Wy90JaQkym68McR%2BeLgO2%2BOa3RRuXBW0b8KuMI65bExZpiE%2FeyDivJP4o%2FoheBRGRsSRKxgwH0KAtxMoN8oRrC0pRusdb7WE8VqVm9Q%3D%3D"
train = pd.read_csv(tr_url)
#Load test.csv
te_url = "https://storage.googleapis.com/kaggle-competitions-data/kaggle/3136/test.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1514683854&Signature=kWvkVcJWry6aPuMmqWhXwX7yKr9CbR6NJ1RkceOtOhwn1lTmSsi1ZW%2B6xeDNtCHebj5gqPaEHqMgvI72Vqc785cFSwVifCi6LVouztTHQ7MmHU1OdvRxHJemNuUPANHHoTAhNB35bbwaQvx31WaI2DG8q4Xj2Ng2x74uSAcPfv0%2BiCLNi6BW6z%2FYQKbWADJH4PvJe0TLX2QL9bXMxRbBH1xcTh9knkN6aRc0Bz9Gr0IPbC2YBWsOYaYyo3HOOfLAI4D5tqtnR2Vev60pijz9Az3KOUwAR17d32S4WONRIGEcMfBrT8ybrw28N3ACNvXEITm9S5M9m3tgwm3ZNAO3lQ%3D%3D"
test = pd.read_csv(te_url)
#print train.head() and test.head()
print(train.head())
print(test.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
  

In [2]:
#Step 2: Using .describe() method which  summarizes the columns/features of the DataFrame, including the count of observations, mean, max and so on.

#train.describe()
print(train.describe())
#train.shape
print(train.shape)

#test.describe()
print(test.describe())
#test.shape
print(test.shape)

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  
(891, 12)
       PassengerId      Pclass         Age       SibSp       Parch     

In [3]:
#Step 3: Female Survived vs Male Survived
#.value_counts() method for a two-way comparison on the number of males and females that survived

#Passengers Survived vs Passed away in absolute numbers
print(train["Survived"].value_counts())

#Passengers Survived vs Passed away in percentage
t1 = (train["Survived"].value_counts(normalize = True)) * 100
print(t1)

#Male Passengers Survived vs Passed away in absolute numbers
print(train["Survived"][train["Sex"] == 'male'].value_counts())

#Male Passengers Survived vs Passed away in percentage
t2 = (train["Survived"][train["Sex"] == 'male'].value_counts(normalize = True)) * 100
print(t2)

#Female Passengers Survived vs Passed away in absolute numbers
print(train["Survived"][train["Sex"] == 'female'].value_counts())

#Female Passengers Survived vs Passed away in percentage
t3 = (train["Survived"][train["Sex"] == 'female'].value_counts(normalize = True)) * 100
print(t3)

0    549
1    342
Name: Survived, dtype: int64
0    61.616162
1    38.383838
Name: Survived, dtype: float64
0    468
1    109
Name: Survived, dtype: int64
0    81.109185
1    18.890815
Name: Survived, dtype: float64
1    233
0     81
Name: Survived, dtype: int64
1    74.203822
0    25.796178
Name: Survived, dtype: float64


In [4]:
#Step 4: Age factor for survival since it's probable that children were saved first.

#Create new column Child
train["Child"] = float('NaN')

#Assign 1 to Age of passenger <18 for others assign 0
train["Child"][train["Age"] < 18] = 1
train["Child"][train["Age"] >= 18] = 0

#Print Percentage Survival rate for Age <18 and >=18
t4 = (train["Survived"][train["Child"] == 1].value_counts(normalize = True)) * 100
print(t4)

t5 = (train["Survived"][train["Child"] == 0].value_counts(normalize = True)) * 100
print(t5)

#Print Child Column
print(train["Child"])

1    53.982301
0    46.017699
Name: Survived, dtype: float64
0    61.896839
1    38.103161
Name: Survived, dtype: float64
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      NaN
6      0.0
7      1.0
8      0.0
9      1.0
10     1.0
11     0.0
12     0.0
13     0.0
14     1.0
15     0.0
16     1.0
17     NaN
18     0.0
19     NaN
20     0.0
21     0.0
22     1.0
23     0.0
24     1.0
25     0.0
26     NaN
27     0.0
28     NaN
29     NaN
      ... 
861    0.0
862    0.0
863    NaN
864    0.0
865    0.0
866    0.0
867    0.0
868    NaN
869    1.0
870    0.0
871    0.0
872    0.0
873    0.0
874    0.0
875    1.0
876    0.0
877    0.0
878    NaN
879    0.0
880    0.0
881    0.0
882    0.0
883    0.0
884    0.0
885    0.0
886    0.0
887    0.0
888    NaN
889    0.0
890    0.0
Name: Child, Length: 891, dtype: float64


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [5]:
#Step5:Create a copy of test as test_copy add a column of Survived in it this is our first prediction for survival
test_copy = test

#initialize survived to 0
test_copy["Survived"] = 0

#Set survived to 1 if Sex=='female'
test_copy["Survived"][test_copy["Sex"] == 'female'] = 1
print(test_copy["Survived"])

0      0
1      1
2      0
3      0
4      1
5      0
6      1
7      0
8      1
9      0
10     0
11     0
12     1
13     0
14     1
15     1
16     0
17     0
18     1
19     1
20     0
21     0
22     1
23     0
24     1
25     0
26     1
27     0
28     0
29     0
      ..
388    0
389    0
390    0
391    1
392    0
393    0
394    0
395    1
396    0
397    1
398    0
399    0
400    1
401    0
402    1
403    0
404    0
405    0
406    0
407    0
408    1
409    1
410    1
411    1
412    1
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [6]:
#Step6:Using Decision trees importing numpy package and tree from sklearn
# Import the Numpy library
import numpy as np
# Import 'tree' from scikit-learn library
from sklearn import tree

In [7]:
#Step7:Cleaning & Formatting Data
#Sex and Embarked variables are categorical but in a non-numeric format. Thus, we will need to assign each class a unique integer so that Python can handle the information. Embarked also has some missing values which you should impute witht the most common class of embarkation, which is "S".

#Male & Female group to integer
train["Sex"][train["Sex"] == "male"] = 0
train["Sex"][train["Sex"] == "female"] = 1

#Imputing missing embark value with "S".
train["Embarked"] = train["Embarked"].fillna('S')

# Convert the Embarked classes to integer form
train["Embarked"][train["Embarked"] == "S"] = 0
train["Embarked"][train["Embarked"] == "C"] = 1
train["Embarked"][train["Embarked"] == "Q"] = 2

#Print the Sex and Embarked columns
print(train["Sex"])
print(train["Embarked"])

0      0
1      1
2      1
3      1
4      0
5      0
6      0
7      0
8      1
9      1
10     1
11     1
12     0
13     0
14     1
15     1
16     0
17     0
18     1
19     1
20     0
21     0
22     1
23     0
24     1
25     1
26     0
27     0
28     1
29     0
      ..
861    0
862    1
863    1
864    0
865    1
866    1
867    0
868    0
869    0
870    0
871    1
872    0
873    0
874    1
875    1
876    0
877    0
878    0
879    1
880    1
881    0
882    1
883    0
884    0
885    1
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: object
0      0
1      1
2      0
3      0
4      0
5      2
6      0
7      0
8      0
9      1
10     0
11     0
12     0
13     0
14     0
15     0
16     2
17     0
18     0
19     1
20     0
21     0
22     2
23     0
24     0
25     0
26     1
27     0
28     2
29     0
      ..
861    0
862    0
863    0
864    0
865    0
866    1
867    0
868    0
869    0
870    0
871    0
872    0
873    0
874    1
875    1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be se

In [8]:
#

In [9]:
#Step 8:First Decision Tree
#Using scikit-learn and numpy libraries,scikit-learn can be used to create tree objects from the DecisionTreeClassifier class and numpy arrays as inputs and therefore we will need to create those from the DataFrame that we already have.

#fill nan with median age
train["Age"] = train["Age"].fillna(train["Age"].median())

#target and features
#target: A 1D numpy array containing the target from the train data. (Survival in this case)
#features: A multidimensional numpy array containing the features/predictors from the train data. (ex. Sex, Age)
target = train["Survived"].values
features = train[["Pclass", "Sex", "Age", "Fare"]].values

#print target and features(optional)
print(target)
print(features)

#Fitting Decision tree
my_tree = tree.DecisionTreeClassifier()
my_tree = my_tree.fit(features, target)

#importance and score of the included features using .feature_importances_ and .score()(to compute mean accuracy)
print(my_tree.feature_importances_)
print(my_tree.score(features, target))


[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [10]:
#After Step 8 we come to know that Passenger Fare is the most imp feature

In [11]:
#Step 9: Predict and Submit to Kaggle
#First, you make use of the .predict() method. You provide it the model (my_tree), the values of features from the dataset for which predictions need to be made (test). To extract the features we will need to create a numpy array in the same way as we did when training the model. However, we need to take care of a small but important problem first. There is a missing value in the Fare feature that needs to be imputed.

#Male & Female group to integer
test["Sex"][test["Sex"] == "male"] = 0
test["Sex"][test["Sex"] == "female"] = 1

#fill nan with median age
test["Age"] = test["Age"].fillna(test["Age"].median())

#impute missing fare value
test.Fare[152] = test.Fare.median()

#Extract features from test as we did from train
test_features = test[["Pclass", "Sex", "Age", "Fare"]].values
print(test_features)
#Make predictions
my_prediction = my_tree.predict(test_features)
print(my_prediction)

#Next, you need to make sure your output is in line with the submission requirements of Kaggle: a csv file with exactly 418 entries and two columns: PassengerId and Survived. Then use the code provided to make a new data frame using DataFrame(), and create a csv file using to_csv() method from Pandas.
PassengerId =np.array(test["PassengerId"]).astype(int)
my_solution = pd.DataFrame(my_prediction, PassengerId, columns = ["Survived"])
print(my_solution)

# Check that your data frame has 418 entries
print(my_solution.shape)

# Write your solution to a csv file with the name my_solution.csv
my_solution.to_csv("my_solution_one.csv", index_label = ["PassengerId"])

#Great! You just created your first decision tree. Download your csv file, and submit the created csv to Kaggle to see the result of your effort.

[[3 0 34.5 7.8292]
 [3 1 47.0 7.0]
 [2 0 62.0 9.6875]
 ..., 
 [3 0 38.5 7.25]
 [3 0 27.0 8.05]
 [3 0 27.0 22.3583]]
[0 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 1 0 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0
 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0
 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1
 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0
 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1
 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 1 0
 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 0 0 1 0 0 0]
      Survived
892          0
893  

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


In [12]:
#After Submitting the above solution on kaggle my score was 56% so to improve it we perform overfitting,feature engineering and apply random forests.

In [13]:
#Overfitting: Good performance on the training data, poor generliazation to new data.
#Control overfitting by setting "max_depth" and "min_samples_split"
#The max_depth parameter determines when the splitting up of the decision tree stops.
#The min_samples_split parameter monitors the amount of observations in a bucket. If a certain threshold is not reached (e.g minimum 10 passengers) no further splitting can be done.

#create features_one with some added features
features_one = train[["Pclass","Age","Sex","Fare", "SibSp","Parch" ,"Embarked"]].values

#"max_depth" and "min_samples_split"
max_depth = 10
min_samples_split = 5
my_tree_one = tree.DecisionTreeClassifier(max_depth = 10, min_samples_split = 5, random_state = 1)
my_tree_one = my_tree_one.fit(features_one,target)

#Print the score of the new decison tree
print(my_tree_one.score(features_one,target))

0.905723905724


In [14]:
#Feature Engineering
#here we add a extra column "family_size" to the train data which is a new feature and combination of "SibSp" and "Parch" plus one(the observation itself)

#Create train_two
train_two = train.copy()

#Now add "family_size" column to train_two
train_two["family_size"] = train["SibSp"] + train["Parch"] + 1

#Add the feature "family_size"
features_two = train_two[["Pclass", "Sex", "Age", "Fare", "SibSp", "Parch", "family_size"]].values

# Define the tree classifier, then fit the model
my_tree_two = tree.DecisionTreeClassifier()
my_tree_two = my_tree_two.fit(features_two,target)

# Print the score of this decision tree
print(my_tree_two.score(features_two, target))


0.979797979798


In [21]:
#Random Forest:if you have trained 3 trees with 2 saying a passenger in the test set will survive and 1 says he will not, the passenger will be classified as a survivor

# Import the `RandomForestClassifier`
from sklearn.ensemble import RandomForestClassifier

# We want the Pclass, Age, Sex, Fare,SibSp, Parch, and Embarked variables
features_forest = train[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch", "Embarked"]].values

# Building and fitting my_forest
forest = RandomForestClassifier(max_depth = 10, min_samples_split=2, n_estimators = 100, random_state = 1)
my_forest = forest.fit(features_forest, target)

# Print the score of the fitted random forest
print(my_forest.score(features_forest, target))

test["Embarked"][test["Embarked"] == "S"] = 0
test["Embarked"][test["Embarked"] == "C"] = 1
test["Embarked"][test["Embarked"] == "Q"] = 2


# Compute predictions on our test set features then print the length of the prediction vector
test_features = test[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch", "Embarked"]].values
pred_forest = my_forest.predict(test_features)
print(len(pred_forest))
#print(test_features)


PassengerId =np.array(test["PassengerId"]).astype(int)
my_solution1 = pd.DataFrame(pred_forest, PassengerId, columns = ["Survived"])
print(my_solution1)

# Check that your data frame has 418 entries
print(my_solution1.shape)

# Write your solution to a csv file with the name my_solution.csv
my_solution1.to_csv("my_solution_four.csv", index_label = ["PassengerId"])


0.939393939394
418
      Survived
892          0
893          0
894          0
895          0
896          0
897          0
898          0
899          0
900          1
901          0
902          0
903          0
904          1
905          0
906          1
907          1
908          0
909          0
910          0
911          0
912          1
913          0
914          1
915          1
916          1
917          0
918          1
919          0
920          0
921          0
...        ...
1280         0
1281         0
1282         0
1283         1
1284         0
1285         0
1286         0
1287         1
1288         0
1289         1
1290         0
1291         0
1292         1
1293         0
1294         1
1295         0
1296         0
1297         0
1298         0
1299         0
1300         1
1301         1
1302         1
1303         1
1304         0
1305         0
1306         1
1307         0
1308         0
1309         1

[418 rows x 1 columns]
(418, 1)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
